### ISSUE TITLE
Please update for Labview 2016 and newer

### ISSUE THREAD

**Issue by teslaeng** [ni/python_labview_automation#2]

**Comment by neilvana** [comment]
I believe the VIs are distributed as source only so they should work with LabVIEW 2016.  Is there a specific problem you are running into with LabVIEW 2016 and newer?

**Comment by neilvana** [comment]
You may just be running with:

lv = LabVIEW()

If you have multiple versions of LabVIEW installed you need to specify which one you want to control:

lv = LabVIEW(version="2016", bitness="x86")

**Comment by teslaeng** [comment]
Thanks for the support explicitly adding the version tags was what I needed.
